
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import Project.ConnnectionProvider;
import java.awt.Color;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rmind
 */
public class Booking extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        lb1.addMouseListener(this);
        lb2.addMouseListener(this);
        lb3.addMouseListener(this);
        lb4.addMouseListener(this);
        lb5.addMouseListener(this);
        lb6.addMouseListener(this);
        lb7.addMouseListener(this);
        lb8.addMouseListener(this);
        lb9.addMouseListener(this);
        lb10.addMouseListener(this);
        lb11.addMouseListener(this);
        lb12.addMouseListener(this);
    }
    
    int seatno = 0;
    
    public void Bill()
    {
        String customer = txtcust.getText();
        int seats1 = seatno;
        String price = txtprice.getText();
        SimpleDateFormat date_form = new SimpleDateFormat("dd-MM-yyyy");
        String date = date_form.format(txtdate.getDate());
        
        txtbill.setText("*******************************************\n");
        txtbill.setText("********************Bill*******************\n");
        txtbill.setText("*******************************************\n");
        txtbill.setText(txtbill.getText()+"Customer" + "\t"+customer+ "\n");
        txtbill.setText(txtbill.getText()+"Seats" + "\t"+seats1+ "\n");
        txtbill.setText(txtbill.getText()+"Price" + "\t"+price+ "\n");
        txtbill.setText(txtbill.getText()+"Date" + "\t"+date+ "\n");
        txtbill.setText(txtbill.getText()+"\n");
        txtbill.setText(txtbill.getText()+"***********Thank You Visit Again****************\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcust = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfrom = new javax.swing.JComboBox<>();
        txtto = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 150));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("American Captain", 0, 24)); // NOI18N
        jLabel1.setText("Bus Reservation System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 6, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 75, -1, -1));

        txtcust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 72, 187, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb1.setBackground(new java.awt.Color(255, 255, 255));
        lb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb1.setText("1");

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb2.setText("2");

        lb3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb3.setText("3");

        lb4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb4.setText("4");

        lb5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb5.setText("5");

        lb6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb6.setText("6");

        lb7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb7.setText("7");

        lb8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb8.setText("8");

        lb9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb9.setText("9");

        lb10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb10.setText("10");

        lb11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb11.setText("11");

        lb12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb12.setText("12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(lb2)
                    .addComponent(lb3)
                    .addComponent(lb4)
                    .addComponent(lb5)
                    .addComponent(lb6))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb7)
                    .addComponent(lb8)
                    .addComponent(lb9)
                    .addComponent(lb10)
                    .addComponent(lb11)
                    .addComponent(lb12))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 255, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Seats");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 295, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 412, -1, -1));

        txtprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 409, 239, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 121, 52));
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 72, 314, 287));

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 72, 280, 377));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("From");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 131, 65, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("To");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 185, 65, -1));

        txtfrom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thoothukudi", "Tirnelveli", "Tenkasi" }));
        getContentPane().add(txtfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 128, 187, -1));

        txtto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chennai", "Coimbatore", "Thiruchirappalli", "Madurai", "Kochi", "Thiruvananthapuram", "Delhi", "Mumbai" }));
        getContentPane().add(txtto, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 182, 187, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 121, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String customer = txtcust.getText();
        String from =(String)txtfrom.getSelectedItem();
        String to =(String)txtto.getSelectedItem();
        int seats1 = seatno;
        String price = txtprice.getText();
        SimpleDateFormat date_form = new SimpleDateFormat("dd-MM-yyyy");
        String date = date_form.format(txtdate.getDate());
        
        try {
            Connection con=ConnnectionProvider.conn();
            Statement st=con.createStatement();
            st.executeUpdate("insert into book values('"+customer+"','"+from+"','"+to+"','"+seats1+"','"+price+"','"+date+"')");
            Bill();
            JOptionPane.showMessageDialog(null,"Seat Booked");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Booking().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcust;
    private com.toedter.calendar.JCalendar txtdate;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JTextField txtprice;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
       
        float num1 = 450;
        float num2 = 450;
        float tax = 90;
        float ans;
        
        if(e.getSource()== lb1)
        {
            seatno = 1;
            lb1.setForeground(Color.RED);
            ans =(num1+num2)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb2)
        {
            seatno = 2;
            ans =(num1+num2+20)+tax;
            lb2.setForeground(Color.RED);
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb3)
        {
            seatno = 3;
            lb3.setForeground(Color.RED);
            ans =(num1+num2+40)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb4)
        {
            seatno = 4;
            lb4.setForeground(Color.RED);
            ans =(num1+num2+60)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb5)
        {
            seatno = 5;
            lb5.setForeground(Color.RED);
            ans =(num1+num2+80)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb6)
        {
            seatno = 6;
            lb6.setForeground(Color.RED);
            ans =(num1+num2+100)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb7)
        {
            seatno = 7;
            lb7.setForeground(Color.RED);
            ans =(num1+num2+120)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb8)
        {
            seatno = 8;
            lb8.setForeground(Color.RED);
            ans =(num1+num2+140)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb9)
        {
            seatno = 9;
            lb9.setForeground(Color.RED);
            ans =(num1+num2+160)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb10)
        {
            seatno = 10;
            lb10.setForeground(Color.RED);
            ans =(num1+num2+180)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb11)
        {
            seatno = 11;
            lb11.setForeground(Color.RED);
            ans =(num1+num2+200)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
        else if(e.getSource()== lb12)
        {
            seatno = 12;
            lb12.setForeground(Color.RED);
            ans =(num1+num2+220)+tax;
            String str = Integer.toString((int) ans);
            txtprice.setText(str);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
